/* 
 * File:   main.cpp
 * Purpose: Homework 
 * Author: Cindy Guijosa
 * Created on July 5, 2015, 6:20 PM
 */

//System Libraries
#include <iostream>
#include <iomanip>
using namespace std;


int main(int argc, char** argv) {
   
    //Declare Variables 
     float  num1,             //Integer entered by user
            num2,             //Integer entered by user 
            num3,             //Integer entered by user
            P,Q,T,            //The Variables associated with class seats and income 
            cA=15,            //The value of a Class A seat
            cB=12,            //The value of a Class B seat 
            cC=9,             //The value of a Class C seat 
            incm;             //Income generated by seats sold
    
    //Prompt User for Number of seats sold
    cout<<"Please enter The number of seats sold starting from Class A"<<endl;
    cin>>num1;
    cout<<"Seats"<<endl;
    cout<<"Now enter for class B"<<endl;
    cin>>num2;
    cout<<"Seats"<<endl;
    cout<<"Now for class C"<<endl;
    cin>>num3;
    cout<<"Seats"<<endl;
    P=cA*num1;
    Q=cB*num2;
    T=cC*num3;
    incm=P+Q+T;
            
    cout<<"The income Generated by the seats sold is ="<<"$"<<incm<<endl;

    return 0;
}

